[tool.poetry]
name = "open-dis-python"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "open_dis_python"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "1.26.4"
setuptools = "^69.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
